### ISSUE TITLE
Loopback stack is broken

### ISSUE THREAD

**Issue by ianpartridge** [appsody/stacks#211]
```
$ appsody init nodejs-loopback
Running appsody init...
Downloading nodejs-loopback template project from https://github.com/appsody/stacks/releases/download/nodejs-loopback-v0.1.0/incubator.nodejs-loopback.templates.scaffold.tar.gz
[Error] Error downloading tar 404 Not Found response trying to download https://github.com/appsody/stacks/releases/download/nodejs-loopback-v0.1.0/incubator.nodejs-loopback.templates.scaffold.tar.gz
```

Looking at https://github.com/appsody/stacks/releases/tag/nodejs-loopback-v0.1.0 the template tar.gz is called `experimental.nodejs-loopback.templates.scaffold.tar.gz` which is wrong.

**Comment by tomleah** [comment]
`nodejs-loopback` was moved from experimental to incubator in `master` but there has been no stack release since so the change will not have been pushed to the CLI yet.

I expect running `appsody init experimental/nodejs-loopback` will still work.

I will release the stacks now to push this update through 🙂

**Comment by ianpartridge** [comment]
Thanks. Please consider the wider issues of how we ended up with `appsody init` broken...

**Comment by pushkarnk** [comment]
Guess the stack is still broken. I did `appsody init nodejs-loopback` which worked and then did an `appsody deploy`, which also works put the pod ends up in the Error state. Here are the logs:

**appsody deploy**
```
Extracting project from development environment
Running command: docker[pull appsody/nodejs-loopback:0.1]
Running command: docker[create --name loopback-extract -v /Users/puskulka/play/kabanero/tekton-pipeline-testing/loopback/:/project/user-app appsody/nodejs-loopback:0.1]
Running command: docker[cp loopback-extract:/project /Users/puskulka/.appsody/extract/loopback]
Running command: docker[rm loopback-extract -f]
Project extracted to /Users/puskulka/.appsody/extract/loopback
Running command: docker[build -t loopback -f /Users/puskulka/.appsody/extract/loopback/Dockerfile /Users/puskulka/.appsody/extract/loopback]
[Docker] Sending build context to Docker daemon  720.9kB
[Docker] Step 1/19 : FROM node:10
[Docker]  ---> e05cbde47b8f
[Docker] Step 2/19 : RUN apt-get update  && apt-get dist-upgrade -y  && apt-get clean  && echo 'Finished installing dependencies'
[Docker]  ---> Using cache
[Docker]  ---> dfe81253989d
[Docker] Step 3/19 : WORKDIR /project
[Docker]  ---> Using cache
[Docker]  ---> 6a428f2e43da
[Docker] Step 4/19 : COPY ./package*.json ./
[Docker]  ---> Using cache
[Docker]  ---> 12d3c03ebd03
[Docker] Step 5/19 : RUN npm install
[Docker]  ---> Using cache
[Docker]  ---> de4d3c2bca6b
[Docker] Step 6/19 : WORKDIR /project/user-app
[Docker]  ---> Using cache
[Docker]  ---> 8769c606d25f
[Docker] Step 7/19 : COPY ./user-app/package*.json ./
[Docker]  ---> Using cache
[Docker]  ---> 01402b0a7b4d
[Docker] Step 8/19 : RUN npm install --production
[Docker]  ---> Using cache
[Docker]  ---> 72644083d9ce
[Docker] Step 9/19 : WORKDIR /project/user-app/node_modules
[Docker]  ---> Using cache
[Docker]  ---> 4d13d63dcace
[Docker] Step 10/19 : FROM node:10-slim
[Docker]  ---> e30512780fab
[Docker] Step 11/19 : RUN apt-get update  && apt-get dist-upgrade -y  && apt-get clean  && echo 'Finished installing dependencies'
[Docker]  ---> Using cache
[Docker]  ---> 5f70e7840fa0
[Docker] Step 12/19 : COPY --chown=node:node . /project
[Docker]  ---> 64789d623a29
[Docker] Step 13/19 : COPY --chown=node:node --from=0 /project/node_modules /project/node_modules
[Docker]  ---> 54db52e44270
[Docker] Step 14/19 : COPY --chown=node:node --from=0 /project/user-app/node_modules /project/user-app/node_modules
[Docker]  ---> f41a7042f5df
[Docker] Step 15/19 : WORKDIR /project
[Docker]  ---> Running in 61d3edd1bebb
[Docker] Removing intermediate container 61d3edd1bebb
[Docker]  ---> 015ca8ffb62e
[Docker] Step 16/19 : ENV NODE_ENV production
[Docker]  ---> Running in f3e5e291375a
[Docker] Removing intermediate container f3e5e291375a
[Docker]  ---> 10296d68aed4
[Docker] Step 17/19 : ENV PORT 3000
[Docker]  ---> Running in 93b1261a5260
[Docker] Removing intermediate container 93b1261a5260
[Docker]  ---> e15a881df339
[Docker] Step 18/19 : USER node
[Docker]  ---> Running in 73c06e3dc6e9
[Docker] Removing intermediate container 73c06e3dc6e9
[Docker]  ---> 2321811fcc6c
[Docker] Step 19/19 : CMD ["npm", "start"]
[Docker]  ---> Running in 66bc90d76b58
[Docker] Removing intermediate container 66bc90d76b58
[Docker]  ---> c7a8cbd4528e
[Docker] Successfully built c7a8cbd4528e
[Docker] Successfully tagged loopback:latest
Built docker image loopback
Tagging Docker image as dev.local/loopback
Generating the KNative yaml deployment file /Users/puskulka/play/kabanero/tekton-pipeline-testing/loopback/appsody-service-949977367.yaml
Generated KNative serving deploy file: /Users/puskulka/play/kabanero/tekton-pipeline-testing/loopback/appsody-service-949977367.yaml
Deploying your project to Kubernetes...
Running command: kubectl[apply -f /Users/puskulka/play/kabanero/tekton-pipeline-testing/loopback/appsody-service-949977367.yaml]
Deployment succeeded.
Running command: kubectl[get rt loopback -o jsonpath="{.status.url}"]
Your deployed service is available at the following URL: ""
```

**kubectl get pods**
```
NAME                                                         READY   STATUS        RESTARTS   AGE
loopback-wgc58-deployment-765bfdf4b8-smss4                   1/3     Error         3          85s
```

**kubectl logs loopback-wgc58-deployment-765bfdf4b8-smss4 -c user-container**
```
> nodejs-loopback@0.1.0 start /project
> node -r source-map-support/register .

Error: Cannot find module './dist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/project/user-app/index.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/project/src/index.ts:12:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-loopback@0.1.0 start: `node -r source-map-support/register .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodejs-loopback@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-08-21T09_12_06_300Z-debug.log
```

**Comment by pushkarnk** [comment]
I think the `dist` directory is created only when `npm run build` is run? This happens only if `appsody run` is issued and because the `dist` directory gets copied over to the image. In a tekton pipeline we  always fail.

**Comment by ianpartridge** [comment]
OK sounds like this is a separate problem to the `appsody init` one. Suggest opening a new issue?

**Comment by pushkarnk** [comment]
Created https://github.com/appsody/stacks/issues/212

**Comment by tomleah** [comment]
Summary of discussion in slack: 

The index being used in this case was the V1 index on master that is being deprecated
```
$ appsody repo list

NAME           URL
*appsodyhub    https://raw.githubusercontent.com/appsody/stacks/master/index.yaml
```

The V1 index was updated with `nodejs-loopback` in incubator when https://github.com/appsody/stacks/pull/95 landed.

We expect the CLI to upgrade this URL to the latest V2 index `https://github.com/appsody/stacks/releases/latest/download/incubator-index.yaml` but this is not currently happening as expected.

**Comment by ianpartridge** [comment]
@tomleah this is fixed now, yeah?

**Comment by tomleah** [comment]
Yes, this is fixed now 🙂 I have created https://github.com/appsody/appsody/issues/223 to help prevent this experience in the future
