### ISSUE TITLE
Error while validating the java-spring-boot2 appsody stack on PPC64LE

### ISSUE THREAD

**Issue by vrushaliinamdar** [appsody/stacks#651]
**Describe the bug**
I am getting following error while validating the java-spring-boot2 appsody stack:
```
[Container] docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/.appsody/appsody-controller\": stat /.appsody/appsody-controller: no such file or directory": unknown.
[Error] Error in 'appsody test': exit status 127
```
and 

```
Docker] [ERROR]
[Docker] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[Docker] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[Docker] java.io.FileNotFoundException: ../*.jar (No such file or directory)
[Docker]        at java.io.FileInputStream.open0(Native Method)
[Docker]        at java.io.FileInputStream.open(FileInputStream.java:212)
[Docker]        at java.io.FileInputStream.<init>(FileInputStream.java:152)
[Docker]        at java.io.FileInputStream.<init>(FileInputStream.java:104)
[Docker]        at sun.tools.jar.Main.run(Main.java:319)
[Docker]        at sun.tools.jar.Main.main(Main.java:1300)
[Docker] The command '/bin/sh -c /project/util/check_version build  && /project/java-spring-boot2-build.sh package  && /project/java-spring-boot2-build.sh createStartScript' returned a non-zero code: 1
[Error] exit status 1
[Error] exit status 1
[Error] exit status 1
```

**To Reproduce**
1. Clone stacks repo
2. Go to incubator/java-spring-boot2 directory
3. execute appsody stack validate command

**Environment Details (please complete the following information):**
- OS: Linux
- ARCH: ppc64le
- Version: 0.3.22 

**If applicable please specify:**
 - CLI version: appsody 0.5.8
 - Stack you are using (including the version): java-spring-boot2 0.3.23 or 0.3.22

PFA full log at - [appsody-validate-0.3.23.log](https://github.com/appsody/stacks/files/4181486/appsody-validate-0.3.23.log)

Any pointers in this regard would be of great help !

**Comment by vrushaliinamdar** [comment]
I guess the problem is with the following command :

`Running command: docker run --rm -p 5005:5005 -p 8080:8080 -p 8443:8443 -p 35729:35729 --name testRunContainer -u 0:0 -e APPSODY_USER=0 -e APPSODY_GROUP=0 -v /root/.appsody/stacks/validating-java-spring-boot2/.:/project/user-app -v /root/.m2/repository:/mvn/repository -v appsody-controller-0.3.4:/.appsody -t --entrypoint /.appsody/appsody-controller dev.local/appsody/java-spring-boot2:0.3 --mode=run`

When I modified this command and executed manually, it worked

`docker run --rm -p 5005:5005 -p 8080:8080 -p 8443:8443 -p 35729:35729 --name testRunContainer -u 0:0 -e APPSODY_USER=0 -e APPSODY_GROUP=0 -v /root/.appsody/stacks/validating-java-spring-boot2/.:/project/user-app -v /root/.m2/repository:/mvn/repository -v /root/go/src/github.com/appsody/controller/package/.:/.appsody -t --entrypoint /.appsody/appsody-controller dev.local/appsody/java-spring-boot2:0.3 --mode=run`

Please note the change:
**-v appsody-controller-0.3.4:/.appsody**
changed to 
**/root/go/src/github.com/appsody/controller/package/.:/.appsody**

**Comment by neeraj-laad** [comment]
When you execute `appsody run/test/debug`, the CLI should download appsody controller and set up a named volume for you.

Looks like this is not happening as expected in this case.
